import localFont from "next/font/local";
import "./globals.css";
// import 'tailwindcss'
import AppHeader from "@/app/ui/AppHeader";
import StoreProvider from "@/app/store/StoreProvider";


const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata = {
    title: "Manyasha Store",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (
        <html lang="en" data-theme="fantasy">
        <head>
            <meta charSet="UTF-8"/>
            <meta name="viewport" content="width=device-width, initial-scale=1.0"/>


            {/*<meta name="theme-color" content="#000000"/>*/}

            <title>Manyasha Store</title>
            {/*<link rel="apple-touch-icon" href="%PUBLIC_URL%/logo192.png"/>*/}

            {/*<link rel="manifest" href="%PUBLIC_URL%/manifest.json"/>*/}
        </head>
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        <StoreProvider>
            <div className="flex flex-col m-0 text-black min-h-screen">
            <header className="flex flex-col border-y-green-900">
                    <AppHeader/>
                </header>
                <main className='content'>
                    {children}
                </main>
                {/*<footer className={'footer'}>*/}
                {/*    <div className={'footer-company-name'} style={{alignItems: 'flex-end'}}>2024 © Manyasha Store</div>*/}
                {/*    <div>*/}

                {/*    </div>*/}
                {/*    /!*<div className={'bank-cards'}>*!/*/}
                {/*    /!*    <div className={'card visa'}><img src={'visa-card.png'} alt={'visa'}/></div>*!/*/}
                {/*    /!*    <div className={'card'}><img src={'master.png'} alt={'visa'}/></div>*!/*/}
                {/*    /!*    <div className={'card'}><img src={'ypay.png'} alt={'visa'}/></div>*!/*/}
                {/*    /!*    <div className={'card'}><img src={'mir.png'} alt={'visa'}/></div>*!/*/}
                {/*    /!*</div>*!/*/}
                {/*</footer>*/}
            </div>
        </StoreProvider>
        </body>
        </html>
    );
}
