// "use client"
import localFont from "next/font/local";
import "./globals.css";
// import 'tailwindcss'
import AuthHeader from "@/app/ui/navbars/AuthHeader";
import StoreProvider from "@/app/store/StoreProvider";
import {useAppSelector} from "@/app/lib/hooks";
import AppFooter from "@/app/ui/AppFooter";
import ReduxLoader from "@/app/ui/loaders/ReduxLoader";
import ScrollToTopComponent from "@/app/common/ScrollToTopComponent";


const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata = {
    title: "Manyasha Store",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {

    //      console.log('cart layout', cart);

    return (
        <html lang="en" data-theme="emerald">
        <head>
            <meta charSet="UTF-8"/>
            <meta name="viewport" content="width=device-width, initial-scale=1.0"/>


            {/*<meta name="theme-color" content="#000000"/>*/}

            <title>Manyasha Store</title>
            <link rel="icon" href="/favicon-2.ico"/>

            {/*<link rel="apple-touch-icon" href="%PUBLIC_URL%/logo192.png"/>*/}

            {/*<link rel="manifest" href="%PUBLIC_URL%/manifest.json"/>*/}
            {/*<script src="https://api-maps.yandex.ru/v3/?apikey=YOUR_API_KEY&lang=en_US"></script>*/}
        </head>
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        <StoreProvider>
            <div className="flex flex-col m-0 p-0 text-black w-full max-w-full min-h-screen">
                <header className="flex flex-col w-full border-y-green-900 ">
                    <AuthHeader/>
                    <ReduxLoader/>
                </header>
                <main className='flex w-full mx-auto mb-10 overflow-y-auto overflow-hidden '>
                    {children}
                </main>

                <AppFooter/>
                <ScrollToTopComponent/>
            </div>


        </StoreProvider>
        </body>
        </html>
    );
}
